# Generated by Django 4.0.4 on 2022-06-10 13:23

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Strona', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='money',
        ),
        migrations.RemoveField(
            model_name='data',
            name='upgrade1',
        ),
        migrations.AddField(
            model_name='data',
            name='name',
            field=models.CharField(default='Get Rick Rolled', max_length=50),
        ),
        migrations.AddField(
            model_name='data',
            name='url',
            field=embed_video.fields.EmbedVideoField(default='https://www.youtube.com/watch?v=dQw4w9WgXcQ'),
        ),
    ]
